name: Build & Publish

on:
  push:

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      current_version_exists: ${{ steps.version_check.outputs.current_version_exists }}
      version:        ${{ steps.version_check.outputs.package_version }}
      package_name:   ${{ steps.version_check.outputs.package_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Check package version on all index
        id: version_check
        uses: MathieuMoalic/action-python-package-new-version@v3
        with:
          index: test.pypi.org

  build:
    runs-on: ubuntu-latest
    needs: version-check
    if: ${{ needs.version-check.outputs.current_version_exists == 'false' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Build distributions
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/